# Generated by Django 4.2.3 on 2023-07-04 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('Description', models.CharField(max_length=2000)),
                ('Price', models.FloatField()),
                ('Stock', models.IntegerField()),
                ('Image', models.CharField(max_length=3000)),
            ],
        ),
    ]
